name: Python App CI/CD Pipeline with AWS Deployment

on:
  push:
    branches:
      - stage-5

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r requirements.txt

    # Run tests (Placeholder for actual tests)
    - name: Run tests
      run: |
        echo "Run tests"

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Deploy to EC2 Auto Scaling Groups
    - name: Deploy to EC2 Auto Scaling Groups
      run: |
        # Split comma-separated ASG names into array
        IFS=',' read -ra ASG_NAMES <<< "${{ secrets.ASG_NAMES }}"
        
        # Deploy to each Auto Scaling Group
        for ASG_NAME in "${ASG_NAMES[@]}"; do
          # Trim whitespace
          ASG_NAME=$(echo "$ASG_NAME" | xargs)
          echo "Deploying to Auto Scaling Group: $ASG_NAME"
          
          # Get all instance IDs in the current Auto Scaling Group
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name $ASG_NAME \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text)
          
          # Deploy to each instance in the current ASG
          for INSTANCE_ID in $INSTANCE_IDS; do
            echo "Deploying to instance: $INSTANCE_ID in ASG: $ASG_NAME"
            aws ssm send-command \
              --instance-ids $INSTANCE_ID \
              --document-name "AWS-RunShellScript" \
              --parameters commands=["export GITHUB_TOKEN=${{ secrets.TOKEN }} && sudo -u ubuntu bash /home/ubuntu/chatbot-app-in-AWS/update_app.sh"] \
              --comment "Deploying application update to ASG $ASG_NAME instance $INSTANCE_ID"
          done
        done
